name: Run Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Setup pynput
      run: |
        echo $DISPLAY
    - name: Run headless test
      uses: coactions/setup-xvfb@v1
      with:
        run: echo $DISPLAY
#    - name: Test with pytest
#      run: |
#        make coverage
